### ISSUE TITLE
Categories Section

### ISSUE THREAD

**Issue by mishramonalisha76** [ChainWhiZ/chainwhiz-dapp-v2#12]
Title: Create the section indicating the several categories chain whiz bring bounties in.

Task Description: Create the section indicating the several categories chain whiz bring bounties in.

Start date: 24th october 2022

ETA: 25th october 2022

**Comment by Xand6r** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/38471362/197758292-21a42be9-d5da-470a-90f8-74cf928968d5.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/38471362/197759110-5d8d0aaf-0a70-4690-b542-5dab3df7c2c3.png">
