### ISSUE TITLE
Create Bounties dropdown

### ISSUE THREAD

**Issue by Xand6r** [ChainWhiZ/chainwhiz-dapp-v2#34]
Title:  Create the dropdown for the bounties section of the application

Task Description:  Create the dropdown for the bounties section of the application.
<img width="900" alt="Screenshot 2022-10-27 at 14 29 45" src="https://user-images.githubusercontent.com/38471362/198298061-78f41f22-6dbb-44ba-a865-9ddbaf8ff885.png">

Start date: 27th october 2022

ETA: 28th october 2022

**Comment by Ladeee** [comment]
done
